max_width = 150
comment_width = 150
wrap_comments = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "crate"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
use_field_init_shorthand = true